language: node_js
node_js:
  - "10"
notifications:
  email: false
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn --frozen-lockfile --non-interactive
jobs:
  include:
    - stage: test
      name: 'Lint and Test'
      before_script:
        - yarn global add codecov
      script:
        - yarn run lint
        - yarn run test
        - yarn run test:coverage
      after_success:
        - codecov
